apiVersion: v1
kind: Pod
metadata:
  name: cyberwise
spec:
  containers:
  - name: cyberwise
    image: marvinkilo/cyberwise:latest
    ports:
    - containerPort: 5000
    resources:
      limits:
        memory: "128Mi"
        
